name: shoe_shop_app
description: A professional shoe shop app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Add assets here
  assets:
    - assets/images/herophoto.png
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/4.jpg
    - assets/images/login.jpg
    - assets/images/profile.jpeg